//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Orders = new HashSet<Order>();
        }

        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter the product name.")]
        public string ProductName { get; set; }

        [Required(ErrorMessage = "Please enter the product price.")]
        [RegularExpression(@"^-?\d*\.?\d+$", ErrorMessage = "Please enter a valid price.")]
        public string ProductPrice { get; set; }

        [Required(ErrorMessage = "Select Cetegory")]
        [Range(1, int.MaxValue, ErrorMessage = "Select Cetegory")]
        public int CetegoryId { get; set; }

        [Required(ErrorMessage = "Give a description about product")]
        public string Description { get; set; }


        [Required(ErrorMessage = "Please choose an image.")]
        public HttpPostedFileBase File { get; set; }


        public string ImageLink { get; set; }

        public virtual Cetegory Cetegory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
