//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using WebApplication1.CustomValidation;

namespace WebApplication1.Entity
{


    public partial class Student
    {
        public int Id { get; set; }

        [Required(ErrorMessage = " provide Name")]
        [MaxLength(25, ErrorMessage = "Max 25 Character")]
        [MinLength(5, ErrorMessage = "Min 5 Character")]
        public string Name { get; set; }

        [Required(ErrorMessage = " provide Email")]
        [MaxLength(25, ErrorMessage = "Max 30 Character")]
        [MinLength(5, ErrorMessage = "Min 5 Character")]
        public string Email { get; set; }


        [Required(ErrorMessage = " provide Password")]
        [MaxLength(25, ErrorMessage = "Max 15 Character")]
        [MinLength(5, ErrorMessage = "Min 5 Character")]
        public string Password { get; set; }

        [Required]
        public string Gender { get; set; }


        [Required(ErrorMessage = "provide Phone number")]
        [RegularExpression("^01[0-9]+", ErrorMessage = "Phone number must start with 01")]
        [StringLength(11, MinimumLength = 11, ErrorMessage = "Phone number must be 11 characters long")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Enter Date of birth")]
        [Min18Year]
        public System.DateTime Dob { get; set; }
    }
}
